---
categories:
  - horror
  - comedy
  - sci-fi
  - romance
  - documentary
  - action
  - anime
  - foreign
  - thriller
  - marathon

defaultPosterPath: 'static/generic-movie-poster.jpg'
...
